### ISSUE TITLE
Improved generation of the summary Yaml file

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/blobtoolkit#77]
### Description of feature

Update the input config to fix the summary YAML generated

**Comment by muffato** [comment]
In my tests (https://github.com/sanger-tol/blobtoolkit/issues/91#issuecomment-1936255635), this is the minimal Yaml file a user has to provide for a draft assembly

```yml
assembly:
  level: bar
settings:
  foo: 0
similarity:
  diamond_blastx:
    foo: 0
taxon:
  class: class_name
  family: family_name
  genus: genus_name
  kingdom: kingdom_name
  name: species_name
  order: order_name
  phylum: phylum_name
  superkingdom: superkingdom_name
  taxid: 0
```

None of the values matter, but the keys have to be present.

- The keys inside `taxon:` are required by the [parsing library of `BLOBTK_IMAGES`](https://github.com/blobtoolkit/blobtk/blob/0.5.3/rust/src/blobdir.rs#L85-L101)
- Everything else is required by `BLOBTOOLKIT_METADATA` when making the `*.metadata.yaml`. The script just copies whatever content is in the input Yaml.
